### ISSUE TITLE
InputIterator?

### ISSUE THREAD

**Issue by ColinH** [LPeter1997/CppCmb#3]
The documentation says that CppCmb works on an InputIterator for tokens, but I'm wondering, don't you actually require a ForwardIterator (that allows you to perform backtracking)?

For example consider something with a structure like `alt< seq< one, one, one >, one >` with an input of two tokens, where you are effectively backtracking to let the second branch of the `alt` start at the same position as the first...

**Comment by LPeter1997** [comment]
Yes, you are right. I forgot that `InputIterator` does not guarantee multiple passes. Thank you for the contribution!
